<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251031WorkSchedules extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add work_patterns and work_overrides tables for shared work schedules';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE work_patterns (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, family_id INT NOT NULL, owner_id INT NOT NULL, cycle_length SMALLINT NOT NULL, start_date DATE NOT NULL, pattern JSON NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_WORK_PATTERNS_FAMILY ON work_patterns (family_id)');
        $this->addSql('CREATE INDEX IDX_WORK_PATTERNS_OWNER ON work_patterns (owner_id)');
        $this->addSql('ALTER TABLE work_patterns ADD CONSTRAINT FK_WORK_PATTERNS_FAMILY FOREIGN KEY (family_id) REFERENCES families (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE work_patterns ADD CONSTRAINT FK_WORK_PATTERNS_OWNER FOREIGN KEY (owner_id) REFERENCES users (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');

        $this->addSql('CREATE TABLE work_overrides (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, pattern_id INT NOT NULL, date DATE NOT NULL, value SMALLINT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_PATTERN_DATE ON work_overrides (pattern_id, date)');
        $this->addSql('CREATE INDEX IDX_WORK_OVERRIDES_PATTERN ON work_overrides (pattern_id)');
        $this->addSql('ALTER TABLE work_overrides ADD CONSTRAINT FK_WORK_OVERRIDES_PATTERN FOREIGN KEY (pattern_id) REFERENCES work_patterns (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE work_overrides DROP CONSTRAINT IF EXISTS FK_WORK_OVERRIDES_PATTERN');
        $this->addSql('ALTER TABLE work_patterns DROP CONSTRAINT IF EXISTS FK_WORK_PATTERNS_OWNER');
        $this->addSql('ALTER TABLE work_patterns DROP CONSTRAINT IF EXISTS FK_WORK_PATTERNS_FAMILY');
        $this->addSql('DROP TABLE IF EXISTS work_overrides');
        $this->addSql('DROP TABLE IF EXISTS work_patterns');
    }
}

