<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251013Photos extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create photos table for family gallery';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('photos')) {
            $this->addSql('CREATE TABLE photos (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, family_id INT NOT NULL, author_id INT DEFAULT NULL, path VARCHAR(255) NOT NULL, caption TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
            $this->addSql('CREATE INDEX IDX_PHOTO_FAMILY ON photos (family_id)');
            $this->addSql('CREATE INDEX IDX_PHOTO_AUTHOR ON photos (author_id)');
            $this->addSql('ALTER TABLE photos ADD CONSTRAINT FK_PHOTO_FAMILY FOREIGN KEY (family_id) REFERENCES families (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
            $this->addSql('ALTER TABLE photos ADD CONSTRAINT FK_PHOTO_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS photos');
    }
}

