<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20251013ContactMessages extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create contact_messages table to store contact form submissions';
    }

    public function up(Schema $schema): void
    {
        if (!$schema->hasTable('contact_messages')) {
            $this->addSql('CREATE TABLE contact_messages (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, from_email VARCHAR(180) NOT NULL, body TEXT NOT NULL, status VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        }
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS contact_messages');
    }
}

